### ISSUE TITLE
Can not export detection model to onnx

### ISSUE THREAD

**Issue by xskopa03** [OpenGVLab/InternImage#102]
Hello, 

I am trying to export the cascade_internimage_xl_fpn_3x_coco.pth and run the onnx engine with tensorrt in C++ but I am failing.

I did all the steps in the detection readme. Current installed cuda is 11.3 with cudnn 8.2.2.26. Installed the DCNv3-1.0+cu113torch1.11.0-cp37-cp37m-linux_x86_64.whl via python pip.

When I try to execute deploy.py:

<pre>
python deploy.py ./deploy/configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py ./configs/coco/cascade_internimage_xl_fpn_3x_coco.py cascade_internimage_xl_fpn_3x_coco.pth ./deploy/demo.jpg --work-dir "./work_dir/" --device cuda --dump-info
</pre>

the output is:

<pre>
Traceback (most recent call last):
  File "deploy.py", line 310, in <module>
    main()
  File "deploy.py", line 136, in main
    device=args.device)
  File "/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 263, in get_deploy
    deploy_cfg, model_cfg, work_dir=work_dir, device=device)
  File "/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 62, in get_model_name_customs
    model_cfg=model_cfg, deploy_cfg=deploy_cfg, device=device)
  File "/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/codebase/__init__.py", line 36, in import_codebase
    codebase.register_all_modules()
  File "/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 36, in register_all_modules
    from mmdet.utils.setup_env import register_all_modules
ImportError: cannot import name 'register_all_modules' from 'mmdet.utils.setup_env' (/home/jakub/.conda/envs/internimage/lib/python3.7/site-packages/mmdet/utils/setup_env.py)
</pre>

Could you give me please advice how to make it work?  Thank you.

**Comment by firatbey** [comment]
I figured it out. You need to use `master` branch of mmdeploy instead of the `main` branch

**Comment by jeonga0303** [comment]
Did you solve that issue?
