### ISSUE TITLE
MultiGpu-Cluster

### ISSUE THREAD

**Issue by aliman80** [OpenGVLab/InternImage#103]
Hi, Thank you very much for your constant support without which things would have been too challenging. I am able to sucessfully run the code and got results on Single GPU. Now i am trying to create environment for multiGPU and clusters but when i try to compile ops_dcnv3 by running sh make.sh or python seetup.py i get following error; Although relevant CUDA is available. Is this issue with my settings or am i missing some thing. Thanks again

This is the error:::
cd/ops_dcvnc3
python setup.py 
No CUDA runtime is found, using CUDA_HOME='/apps/local/11.3'
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 46, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

**Comment by czczup** [comment]
Hi @aliman80, in a GPU cluster (such as slurm) you need to apply for a GPU card to compile dcnv3.

**Comment by aliman80** [comment]
Thanks agian ,you mean i need to have specific GPU where i can compile dconv3?
