### ISSUE TITLE
CUDA problems during traning on custom data using single GPU

### ISSUE THREAD

**Issue by Wmelon0325** [OpenGVLab/InternImage#104]
My development environment is 

**single gpu A6000 48GB **
python              3.7.16
torch                 1.12.0
torch-geometric       1.7.2
torchaudio            0.12.0
torchvision           0.13.0

I have a problem occurred during training as below.

Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 252, in main
    meta=meta)
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/mmdet/apis/train.py", line 247, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/user/anaconda3/envs/Intern/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
**RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**

Is this out of memory problem?
Could you give me a advice, please ?
Thank you

**Comment by czczup** [comment]
Thanks for your feedback. This error may be due to unenough GPU memory. How much GPU memory do you have?

**Comment by IanLee-Dio** [comment]
Hi @czczup Thank you guys for the amazing work.
Currently I'm using single gpu with 10GB memory, when I'm trying to run **segmentation** image_demo.py with config:configs/ade20k/**upernet_internimage_t_512_160k_ade20k**.py
I got an CUDA out of memory Error:
2023-05-15 23:11:44,792 - mmseg - INFO - using core type: DCNv3
2023-05-15 23:11:44,792 - mmseg - INFO - using activation layer: GELU
2023-05-15 23:11:44,792 - mmseg - INFO - using main norm layer: LN
2023-05-15 23:11:44,793 - mmseg - INFO - using dpr: linear, 0.3
2023-05-15 23:11:44,793 - mmseg - INFO - level2_post_norm: False
2023-05-15 23:11:44,793 - mmseg - INFO - level2_post_norm_block_ids: None
2023-05-15 23:11:44,793 - mmseg - INFO - res_post_norm: False
/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmseg/models/losses/cross_entropy_loss.py:236: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  'Default ``avg_non_ignore`` is False, if you would like to '
load checkpoint from local path: checkpoint_dir/upernet_internimage_s_512_160k_ade20k.pth
Traceback (most recent call last):
  File "image_demo.py", line 59, in <module>
    main()
  File "image_demo.py", line 46, in main
    result = inference_segmentor(model, args.img)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmseg/apis/inference.py", line 98, in inference_segmentor
    result = model(return_loss=False, rescale=True, **data)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmseg/models/segmentors/base.py", line 110, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmseg/models/segmentors/base.py", line 92, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 256, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 242, in inference
    output = F.softmax(seg_logit, dim=1)
  File "/xx/xx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/torch/nn/functional.py", line 1834, in softmax
    ret = input.softmax(dim)
RuntimeError: CUDA out of memory. Tried to allocate 7.25 GiB (GPU 0; 9.78 GiB total capacity; 7.56 GiB already allocated; 584.62 MiB free; 7.60 GiB reserved in total by PyTorch)

Any help will be appreciated~~

**Comment by caozhenxiang-kouji** [comment]
Same problem.
Even if I try with the smallest backbone internimage_l_22k_192to384, the error still occurrs.

**Comment by caozhenxiang-kouji** [comment]
> Hi! I have a same problem. Have you solved this problem?

I 've figured it out. It seems that your GPU is too small to run the backward operation. Try with a larger one. I manage to train the InternImage-l with a batchsize of 2 on V100.

**Comment by vvwomen** [comment]
I encountered the same error, I only have one V100s card, and I have adjusted the batch size to 1, but still reported this error。Moreover, I also printed the words "error in dcnv3_col2im_cuda: an illegal memory access was accounted for" on my end。Is there a phenomenon similar to mine? May I ask how to solve it?
