### ISSUE TITLE
(Detection) Checkpoint lost? Eval issue?

### ISSUE THREAD

**Issue by chungminho1** [OpenGVLab/InternImage#161]
Hello, I hope you are doing well.
I am training my custom data.
I'm using cascade_rcnn_r50_fpn.py.
I ran dist_train.sh.

While training, all epochs are trained well but there are a problem.
The error message shows that evaluating process is not done, and also checkpoints are not made.
My data structure looks like this.
```
├── data
    ├──train
    ├──valid
    ├──test
    ├── annotations
        ├── train.coco.json
        ├── valid.coco.json
        ├── test.coco.json
├── config.py
├── configs
    ├── custom
        ├── config_instance.py
```

How can I validate or test on my code?
I would be very thankful for your help.

```
2023-05-22 13:37:57,635 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2023-05-22 13:37:57,635 - mmdet - INFO - Checkpoints will be saved to /InternImage/detection/work_dirs/config_instance by HardDiskBackend.
2023-05-22 13:37:59,776 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 706/706, 75.8 task/s, elapsed: 9s, ETA:     0s

2023-05-22 13:38:10,886 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
2023-05-22 13:38:10,886 - mmdet - ERROR - The testing results of the whole dataset is empty.
/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py:377: UserWarning: Since `eval_res` is an empty dict, the behavior to save the best checkpoint will be skipped in this evaluation.
  'Since `eval_res` is an empty dict, the behavior to save '
2023-05-22 13:38:10,887 - mmdet - INFO - Epoch(val) [1][353]
2023-05-22 13:38:13,010 - mmdet - INFO - Saving checkpoint at 2 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 706/706, 74.8 task/s, elapsed: 9s, ETA:     0s

2023-05-22 13:38:23,035 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
2023-05-22 13:38:23,036 - mmdet - ERROR - The testing results of the whole dataset is empty.
2023-05-22 13:38:23,036 - mmdet - INFO - Epoch(val) [2][353]
2023-05-22 13:38:25,150 - mmdet - INFO - Saving checkpoint at 3 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 706/706, 75.8 task/s, elapsed: 9s, ETA:     0s
```

**Comment by chungminho1** [comment]
I think 'num_classes' have to be changed.
Where can I fix it?
Only adding classes on my config file didn't solve my error.

**Comment by chungminho1** [comment]
I changed num_classes in model.py, and added num_classes and classes=[ ] in my custom config file.
But now, I met a new error.
Is it related to num_classes? or other else?

```
2023-05-28 07:26:16,615 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2023-05-28 07:26:16,615 - mmdet - INFO - Checkpoints will be saved to /InternImage/detection/work_dirs/config_instance by HardDiskBackend.
Traceback (most recent call last):
  File "./train.py", line 247, in <module>
    main()
  File "./train.py", line 243, in main
    meta=meta)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 220, in __getitem__
    data = self.prepare_train_img(idx)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 243, in prepare_train_img
    return self.pipeline(results)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 398, in __call__
    results = self._load_masks(results)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 350, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 350, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 306, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
IndexError: list index out of range

Traceback (most recent call last):
  File "./train.py", line 247, in <module>
    main()
  File "./train.py", line 243, in main
    meta=meta)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 220, in __getitem__
    data = self.prepare_train_img(idx)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 243, in prepare_train_img
    return self.pipeline(results)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 398, in __call__
    results = self._load_masks(results)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 350, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 350, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 306, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
IndexError: list index out of range

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13338) of binary: /opt/conda/envs/internimage/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/internimage/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/internimage/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-28_07:26:19
  host      : 0ce9050d4ee2
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 13339)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-28_07:26:19
  host      : 0ce9050d4ee2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13338)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by chungminho1** [comment]
Solved.

**Comment by noweymik** [comment]
I also encountered the same error. How did you resolve it?

**Comment by LaranjaCat** [comment]
Hey, I just had the same issue, can you please tell me whats the solution?
