### ISSUE TITLE
[Question] ValueError: need at least one array to concatenate in group_sampler.py  Description:

### ISSUE THREAD

**Issue by luminous33** [OpenGVLab/InternImage#173]
I am trying to train an object detection model using custom data without segmentation. However, I encountered the following error during the training process:

```python
Traceback (most recent call last):
  File "/data/test/InternImage/detection/train.py", line 247, in <module>
    main()
  File "/data/test/InternImage/detection/train.py", line 237, in main
    train_detector(model,
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 965, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 996, in _reset
    self._try_put_index()
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1230, in _try_put_index
    index = self._next_index()
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/usr/local/anaconda3/envs/intern/lib/python3.9/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
``` 

Steps to reproduce:

Prepare a custom dataset for object detection training without segmentation.
Run the training script.
Expected behavior:
I expect the training process to run without any errors and successfully train the object detection model.

Actual behavior:
The mentioned error occurs during the training process. It seems that self.group_sizes in group_sampler.py is being passed as an empty list [].

Additional information:

I'm using the following versions:
TorchVision: 0.12.0+cu113
OpenCV: 4.7.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.28.1+1929ef4

I would appreciate any help or suggestions on how to resolve this issue. Thank you!

**Comment by Furqan7007** [comment]
Do we have any resolution for this?

**Comment by merchen911** [comment]
I think that CustomDataset._filter_imgs in mmdet/datasets/custom doesn't work. 
Before working this function, the training image path and annotation infos exists.
But after the filtering function, the dataset lost the "self.data_infos" in the object.

**Comment by luminous33** [comment]
> 

I conducted the detection task and confirmed that it performs well even on custom datasets, similar to other training models. I'm wondering if there are any additional measures to consider when working on the detection task

**Comment by luminous33** [comment]
It is confirmed that it is an error about the dataset. In the case of my config file, both the data path and class were specified, but I don't know what the problem is with both datasets and classes read from train.py bringing in coco.
```python
runner = dict(type='EpochBasedRunner', max_epochs=36)
checkpoint_config = dict(interval=5, max_keep_ckpts=3, save_last=True)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [
    dict(
        type='ExpMomentumEMAHook',
        resume_from=None,
        momentum=0.0001,
        priority=49)
]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
CLASSES = (
    'chevrolet_malibu_sedan_2012_2016', 'chevrolet_malibu_sedan_2017_2019',
    'chevrolet_spark_hatchback_2016_2021', 'chevrolet_trailblazer_suv_2021_',
    'chevrolet_trax_suv_2017_2019', 'genesis_g80_sedan_2016_2020',
    'genesis_g80_sedan_2021_', 'genesis_gv80_suv_2020_',
    'hyundai_avante_sedan_2011_2015', 'hyundai_avante_sedan_2020_',
    'hyundai_grandeur_sedan_2011_2016', 'hyundai_grandstarex_van_2018_2020',
    'hyundai_ioniq_hatchback_2016_2019', 'hyundai_sonata_sedan_2004_2009',
    'hyundai_sonata_sedan_2010_2014', 'hyundai_sonata_sedan_2019_2020',
    'kia_carnival_van_2015_2020', 'kia_carnival_van_2021_',
    'kia_k5_sedan_2010_2015', 'kia_k5_sedan_2020_', 'kia_k7_sedan_2016_2020',
    'kia_mohave_suv_2020_', 'kia_morning_hatchback_2004_2010',
    'kia_morning_hatchback_2011_2016', 'kia_ray_hatchback_2012_2017',
    'kia_sorrento_suv_2015_2019', 'kia_sorrento_suv_2020_',
    'kia_soul_suv_2014_2018', 'kia_sportage_suv_2016_2020',
    'kia_stonic_suv_2017_2019', 'renault_sm3_sedan_2015_2018',
    'renault_xm3_suv_2020_', 'ssangyong_korando_suv_2019_2020',
    'ssangyong_tivoli_suv_2016_2020')
work_dir = 'dacon'
auto_resume = False
gpu_ids = [0]

2023-06-12 11:36:22,865 - mmdet - INFO - Set random seed to 2096506123, deterministic: False
2023-06-12 11:36:22,865 - mmdet - INFO - using core type: DCNv3
2023-06-12 11:36:22,865 - mmdet - INFO - using activation layer: GELU
2023-06-12 11:36:22,865 - mmdet - INFO - using main norm layer: LN
2023-06-12 11:36:22,865 - mmdet - INFO - using dpr: linear, 0.4
2023-06-12 11:36:22,865 - mmdet - INFO - level2_post_norm: False
2023-06-12 11:36:22,865 - mmdet - INFO - level2_post_norm_block_ids: None
2023-06-12 11:36:22,865 - mmdet - INFO - res_post_norm: False
2023-06-12 11:36:24,502 - mmdet - WARNING - No pre-trained weights for InternImage, training start from scratch
2023-06-12 11:36:25,142 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2023-06-12 11:36:25,151 - mmdet - INFO - initialize RPNHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01}
2023-06-12 11:36:25,153 - mmdet - INFO - initialize ConvFCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'distribution': 'uniform', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
2023-06-12 11:36:25,190 - mmdet - INFO - initialize ConvFCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'distribution': 'uniform', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
2023-06-12 11:36:25,225 - mmdet - INFO - initialize ConvFCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'distribution': 'uniform', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
[
CocoDataset Train dataset with number of images 0, and instance counts: 
+---------------------+-------+-----------------+-------+--------------------+-------+--------------------+-------+-------------------+-------+
| category            | count | category        | count | category           | count | category           | count | category          | count |
+---------------------+-------+-----------------+-------+--------------------+-------+--------------------+-------+-------------------+-------+
| 0 [person]          | 0     | 1 [bicycle]     | 0     | 2 [car]            | 0     | 3 [motorcycle]     | 0     | 4 [airplane]      | 0     |
| 5 [bus]             | 0     | 6 [train]       | 0     | 7 [truck]          | 0     | 8 [boat]           | 0     | 9 [traffic light] | 0     |
| 10 [fire hydrant]   | 0     | 11 [stop sign]  | 0     | 12 [parking meter] | 0     | 13 [bench]         | 0     | 14 [bird]         | 0     |
| 15 [cat]            | 0     | 16 [dog]        | 0     | 17 [horse]         | 0     | 18 [sheep]         | 0     | 19 [cow]          | 0     |
| 20 [elephant]       | 0     | 21 [bear]       | 0     | 22 [zebra]         | 0     | 23 [giraffe]       | 0     | 24 [backpack]     | 0     |
| 25 [umbrella]       | 0     | 26 [handbag]    | 0     | 27 [tie]           | 0     | 28 [suitcase]      | 0     | 29 [frisbee]      | 0     |
| 30 [skis]           | 0     | 31 [snowboard]  | 0     | 32 [sports ball]   | 0     | 33 [kite]          | 0     | 34 [baseball bat] | 0     |
| 35 [baseball glove] | 0     | 36 [skateboard] | 0     | 37 [surfboard]     | 0     | 38 [tennis racket] | 0     | 39 [bottle]       | 0     |
| 40 [wine glass]     | 0     | 41 [cup]        | 0     | 42 [fork]          | 0     | 43 [knife]         | 0     | 44 [spoon]        | 0     |
| 45 [bowl]           | 0     | 46 [banana]     | 0     | 47 [apple]         | 0     | 48 [sandwich]      | 0     | 49 [orange]       | 0     |
| 50 [broccoli]       | 0     | 51 [carrot]     | 0     | 52 [hot dog]       | 0     | 53 [pizza]         | 0     | 54 [donut]        | 0     |
| 55 [cake]           | 0     | 56 [chair]      | 0     | 57 [couch]         | 0     | 58 [potted plant]  | 0     | 59 [bed]          | 0     |
| 60 [dining table]   | 0     | 61 [toilet]     | 0     | 62 [tv]            | 0     | 63 [laptop]        | 0     | 64 [mouse]        | 0     |
| 65 [remote]         | 0     | 66 [keyboard]   | 0     | 67 [cell phone]    | 0     | 68 [microwave]     | 0     | 69 [oven]         | 0     |
| 70 [toaster]        | 0     | 71 [sink]       | 0     | 72 [refrigerator]  | 0     | 73 [book]          | 0     | 74 [clock]        | 0     |
| 75 [vase]           | 0     | 76 [scissors]   | 0     | 77 [teddy bear]    | 0     | 78 [hair drier]    | 0     | 79 [toothbrush]   | 0     |
+---------------------+-------+-----------------+-------+--------------------+-------+--------------------+-------+-------------------+-------+]
22222222222222222222222222
('person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush')
1111111111111111111111111
``` 
How do i solve this?
