### ISSUE TITLE
No module named 'mmseg'

### ISSUE THREAD

**Issue by MasahiroOgawa** [OpenGVLab/InternImage#208]
I got the above error when I run segmentation inference for my own image as;
```bash
$ CUDA_VISIBLE_DEVICES=0 python image_demo.py data/mine/images/00001.jpg configs/ade20k/upernet_internimage_t_512_160k_ade20k.py    checkpoint_dir/seg/upernet_internimage_t_512_160k_ade20k.pth    --palette ade20k 
```

**Comment by MasahiroOgawa** [comment]
I ran
$ pip install mmseg
But I got below error.
   Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xf1bc9gz/mmseg_124b5f9fc7664f1588525836b5b186d7/setup.py", line 6, in <module>
          reload(sys)
      NameError: name 'reload' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by MasahiroOgawa** [comment]
Instead of using pip, I ran below command. 
$ mim install mmsegmentation
Then it seems I successfully installed mmseg.

But when I ran the inference command again, I got below error.
---
ImportError: cannot import name 'print_log' from 'mmcv' (/home/mas/anaconda3/envs/internimage/lib/python3.7/site-packages/mmcv/__init__.py)

**Comment by MasahiroOgawa** [comment]
The problem of 'print_log' related problem might because I didn't specify the version of mmsegmentation corresponding mmcv-full=1.5.0. 
 The corresponding version is listed [here](https://mmsegmentation.readthedocs.io/en/0.x/faq.html), but in internimage/segmentation/README.md, there is explicit description about the version of mmsegmentation, which is 0.27.0.
 So the proper solution would be
```bash
$ mim install mmsegmentation==0.27.0
```
