### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/gtFine/train/strasbourg/strasbourg_000001_031683_gtFine_labelTrainIds.png'

### ISSUE THREAD

**Issue by niuyixing** [OpenGVLab/InternImage#220]
![image](https://github.com/OpenGVLab/InternImage/assets/29516566/fa239e98-ca61-4505-a6eb-2aa00020c8d9)
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/gtFine/train/strasbourg/strasbourg_000001_031683_gtFine_labelTrainIds.png'

**Comment by niuyixing** [comment]
I have downloaded the cityscaps data set from the official website, as shown in the red box. Every time I do it, I report an error and miss, and every miss is different. I also tried other data set download channels to find the missing images, all without success

**Comment by niuyixing** [comment]
2023-08-13 12:15:15,831 - mmseg - INFO - workflow: [('train', 1)], max: 160000 iters
2023-08-13 12:15:15,831 - mmseg - INFO - Checkpoints will be saved to /home/ubuntu/InternImage-master/segmentation/work_dirs/upernet_internimage_s_512x1024_160k_cityscapes by HardDiskBackend.
Traceback (most recent call last):
  File "./train.py", line 248, in <module>
    main()
  File "./train.py", line 244, in main
    meta=meta)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmseg/datasets/custom.py", line 215, in __getitem__
    return self.prepare_train_img(idx)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmseg/datasets/custom.py", line 232, in prepare_train_img
    return self.pipeline(results)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmseg/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmseg/datasets/pipelines/loading.py", line 132, in __call__
    img_bytes = self.file_client.get(filename)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 993, in get
    return self.client.get(filepath)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 518, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/gtFine/train/hamburg/hamburg_000000_016928_gtFine_labelTrainIds.png'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10032) of binary: /home/ubuntu/miniconda3/envs/internimage/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/miniconda3/envs/internimage/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-13_12:15:37
  host      : niuyixing
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10032)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
![image](https://github.com/OpenGVLab/InternImage/assets/29516566/6aa674ed-36d2-4abc-889d-9f54f0556094)

**Comment by wqzgn** [comment]
老哥你解决这个问题了没，我这边也遇到了这种情况，在自己的电脑上能完美运行，但是把项目丢在服务器上就报这个错，和你的错误一模一样

**Comment by jmm-jmm** [comment]
一模一样

**Comment by jmm-jmm** [comment]
在GitHub能搜到脚本来创建所需文件。见https://github.com/mcordts/cityscapesScripts
