### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xda'.

### ISSUE THREAD

**Issue by Zoey-unavailable** [OpenGVLab/InternImage#35]
hello, thanks for your reply. Last question had solved. But I meet another problem. When I tried to load pre-train model, I met an error:  _pickle.UnpicklingError: invalid load key, '\xda'. It seems that the pre-train model file has broken， isn't it?

Traceback (most recent call last):
  File "/home/zyp/下载/pytorch/InternImage-master/segmentation/mytest.py", line 3, in <module>
    model = **torch.load**(r'checkpoint_dir/upernet_internimage_t_512_160k_ade20k.pth')            
  File "/home/zyp/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zyp/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
**_pickle.UnpicklingError: invalid load key, '\xda'.**

**Comment by czczup** [comment]
Could you please download checkpoint again

**Comment by Zoey-unavailable** [comment]
Thank you for your patient reply!
