### ISSUE TITLE
Using InternImage for Object Detection without Segmentation

### ISSUE THREAD

**Issue by MuMiMaNz** [OpenGVLab/InternImage#43]
Hello,

I hope you are doing well. I am working on a project where I would like to use the InternImage dataset solely for object detection without involving segmentation. I attempted to use it with Cascade RCNN, but I encountered an error during the process.

Here is the error message I received:

`2023-03-15 13:39:35,378 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
2023-03-15 13:39:35,422 - mmdet - INFO - Checkpoints will be saved to /content/drive/MyDrive/FETP/HealthSit/Phase_02_1/InternImage/detection/work_dirs/mod_cascade_internimage_l_fpn_3x_coco by HardDiskBackend.
Traceback (most recent call last):
  File "/content/drive/MyDrive/FETP/HealthSit/Phase_02_1/InternImage/detection/./train.py", line 247, in <module>
    main()
  File "/content/drive/MyDrive/FETP/HealthSit/Phase_02_1/InternImage/detection/./train.py", line 237, in main
    train_detector(model,
  File "/usr/local/lib/python3.9/dist-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.9/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/custom.py", line 220, in __getitem__
    data = self.prepare_train_img(idx)
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/custom.py", line 243, in prepare_train_img
    return self.pipeline(results)
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/pipelines/loading.py", line 398, in __call__
    results = self._load_masks(results)
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/pipelines/loading.py", line 350, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/pipelines/loading.py", line 350, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/usr/local/lib/python3.9/dist-packages/mmdet/datasets/pipelines/loading.py", line 308, in _poly2mask
    elif isinstance(mask_ann['counts'], list):
TypeError: 'NoneType' object is not subscriptable

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4737) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-15_13:39:43
  host      : 9677141c6259
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4737)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================"`

From my understanding, it seems that the CascadeRoIHead might require segmentation annotations. I tried using Faster RCNN with InternImage as well but was unsuccessful. I believe that being able to use InternImage for object detection without segmentation could potentially improve performance in certain scenarios.

Could you please provide any guidance or suggestions on how to achieve this? I would really appreciate your help in resolving this issue.

Thank you very much for your time and assistance.

Best regards,
Suppasit Srisaeng

**Comment by czczup** [comment]
Hi, you can follow the steps below to modify the config:

For example, on COCO dataset, using InternImage for object detection without segmentation,

1. change `cascade_mask_rcnn_r50_fpn.py` to `cascade_rcnn_r50_fpn.py`
2. change `coco_instance.py` to `coco_detection.py`
```
_base_ = [
    '../_base_/models/cascade_rcnn_r50_fpn.py', # here (cascade_mask_rcnn_r50_fpn.py -> cascade_rcnn_r50_fpn.py)
    '../_base_/datasets/coco_instance.py', # here (coco_instance.py -> coco_detection.py)
    '../_base_/schedules/schedule_3x.py',
    '../_base_/default_runtime.py'
]
```
3. If there has a custom `train_pipeline` in this config, you should note to remove `gt_mask` in the `Collect` dict.

```
dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']), # remove gt_mask
```

**Comment by MuMiMaNz** [comment]
@czczup Thanks Zhe Chen! It's working. I running Cascade RCNN with InternImage backbone on my custom dataset. Tomorrow I will show you the performance. Thanks again 😄👍

**Comment by vrk7** [comment]
@MuMiMaNz Could you please share the running notebook?

**Comment by MuMiMaNz** [comment]
@vrk7 https://colab.research.google.com/drive/1zUsR6u12yHX7RCnUK6b7EwnjS-Tj2gjU?usp=sharing
Here is Colab, but you should change config file as Zhe Chen suggestion.

**Comment by iamlvm** [comment]
Based on @czczup's suggestion, I also had to change `with_mask` from `True` to `False`:

`dict(type='LoadAnnotations', with_bbox=True, with_mask=False),`

in the same file (e.g., `mask_rcnn_internimage_t_fpn_3x_coco.py` or `cascade_internimage_l_fpn_3x_coco.py`).
