### ISSUE TITLE
classification train failed, no such file meta_data/train.txt

### ISSUE THREAD

**Issue by whitelilis** [OpenGVLab/InternImage#48]
When train clissification model as doc: it failed.

Traceback (most recent call last):
  File "/home/liuzhe/github/InternImage/classification/main.py", line 661, in <module>
    main(config)
  File "/home/liuzhe/github/InternImage/classification/main.py", line 170, in main
    data_loader_val, data_loader_test, mixup_fn = build_loader(config)
  File "/home/liuzhe/github/InternImage/classification/dataset/build.py", line 58, in build_loader
    dataset_train, config.MODEL.NUM_CLASSES = build_dataset('train',
  File "/home/liuzhe/github/InternImage/classification/dataset/build.py", line 158, in build_dataset
    dataset = ImageCephDataset(root,
  File "/home/liuzhe/github/InternImage/classification/dataset/cached_image_folder.py", line 310, in __init__
    parser = ParserCephImage(root=root,
  File "/home/liuzhe/github/InternImage/classification/dataset/cached_image_folder.py", line 383, in __init__
    with open(osp.join(annotation_root, f'{split}.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'meta_data/train.txt'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 846478) of binary: /home/miniconda3/envs/lz_ray/bin/python

**Comment by ZhenhangHuang** [comment]
Hi, you should organize the dataset paths into meta_data as shown in [L83-L111](https://github.com/OpenGVLab/InternImage/blob/master/classification/README.md?plain=1#L83-L111) before running the training and test.
as follows:
![image](https://user-images.githubusercontent.com/38136888/225883644-f59e5642-283a-4459-8823-49b5c955593a.png)

**Comment by whitelilis** [comment]
Thank you very much。
But I am not using the zip method， I just put the files upder the directories, so as to say, the first method.

**Comment by ZhenhangHuang** [comment]
Thank you for your question, you can do this as follows.
First import the torchvision package
```python 
from torchvision import datasets
```
Then change the way of loading imagenet dataet in [L156-L164](https://github.com/OpenGVLab/InternImage/blob/master/classification/dataset/build.py#L156-L164)
```python 
root = os.path.join(config.DATA.DATA_PATH, prefix)
dataset = datasets.ImageFolder(root, transform=transform)
```
we will update the code later

**Comment by czczup** [comment]
Closing this issue as there has been no activity. Please feel free to reopen if required. Thanks for your feedback and support.

**Comment by jeonga0303** [comment]
When will the code be updated? I don't think it's been fixed yet.
