### ISSUE TITLE
failed to convert seg model on Jetson Orin

### ISSUE THREAD

**Issue by gongchengli** [OpenGVLab/InternImage#66]
Hi all, currently I convert the classification model using the export.py. 
pytorch -> onnx is okay, no error. But onnx -> trt, it fails with:
```
2023-03-27 16:10:55,278 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.Because the file does not exist:
[03/27/2023-16:11:00] [TRT] [E] ModelImporter.cpp:773: While parsing node number 80 [TRTDCNv3 -> "onnx::MatMul_741"]:
[03/27/2023-16:11:00] [TRT] [E] ModelImporter.cpp:774: --- Begin node ---
[03/27/2023-16:11:00] [TRT] [E] ModelImporter.cpp:775: input: "mmdeploy::TRTDCNv3_685"
input: "mmdeploy::TRTDCNv3_710"
input: "mmdeploy::TRTDCNv3_740"
output: "onnx::MatMul_741"
name: "TRTDCNv3_80"
op_type: "TRTDCNv3"
attribute {
  name: "dilation_h"
  i: 1
  type: INT
}
attribute {
  name: "dilation_w"
  i: 1
  type: INT
}
attribute {
  name: "group_channels"
  i: 16
  type: INT
}
attribute {
  name: "group"
  i: 4
  type: INT
}
attribute {
  name: "im2col_step"
  i: 256
  type: INT
}
attribute {
  name: "kernel_h"
  i: 3
  type: INT
}
attribute {
  name: "kernel_w"
  i: 3
  type: INT
}
attribute {
  name: "offset_scale"
  f: 1
  type: FLOAT
}
attribute {
  name: "pad_h"
  i: 1
  type: INT
}
attribute {
  name: "pad_w"
  i: 1
  type: INT
}
attribute {
  name: "stride_h"
  i: 1
  type: INT
}
attribute {
  name: "stride_w"
  i: 1
  type: INT
}
domain: "mmdeploy"

[03/27/2023-16:11:00] [TRT] [E] ModelImporter.cpp:776: --- End node ---
[03/27/2023-16:11:00] [TRT] [E] ModelImporter.cpp:778: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
Traceback (most recent call last):
  ......
    from_onnx(
  File "/home_ext/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 181, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 80 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

Any advices? thx

**Comment by Weiyun1025** [comment]
Thank you for your issue. 

You can refer to issue #39 to solve this error.

**Comment by gongchengli** [comment]
> Thank you for your issue.
> 
> You can refer to issue #39 to solve this error.

Thx, now run the deploy.py file and find this,
```
2023-03-28 07:29:30,122 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
2023-03-28 07:29:30,697 - mmseg - INFO - using core type: DCNv3
2023-03-28 07:29:30,698 - mmseg - INFO - using activation layer: GELU
2023-03-28 07:29:30,698 - mmseg - INFO - using main norm layer: LN
2023-03-28 07:29:30,698 - mmseg - INFO - using dpr: linear, 0.2
2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm: False
2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm_block_ids: None
2023-03-28 07:29:30,698 - mmseg - INFO - res_post_norm: False
/usr/local/lib/python3.8/dist-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: checkpoint_dir/upernet_internimage_t_512_160k_ade20k.pth
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data_ext/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data_ext/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
    torch_model = task_processor.init_pytorch_model(model_checkpoint)
  File "/data_ext/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 105, in init_pytorch_model
    model = init_segmentor(self.model_cfg, model_checkpoint, self.device)
  File "/usr/local/lib/python3.8/dist-packages/mmseg/apis/inference.py", line 35, in init_segmentor
    model.CLASSES = checkpoint['meta']['CLASSES']
KeyError: 'meta'
2023-03-28 07:29:32,888 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by Weiyun1025** [comment]
> > Thank you for your issue.
> > You can refer to issue #39 to solve this error.
> 
> Thx, now run the deploy.py file and find this,
> 
> ```
> 2023-03-28 07:29:30,122 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
> 2023-03-28 07:29:30,697 - mmseg - INFO - using core type: DCNv3
> 2023-03-28 07:29:30,698 - mmseg - INFO - using activation layer: GELU
> 2023-03-28 07:29:30,698 - mmseg - INFO - using main norm layer: LN
> 2023-03-28 07:29:30,698 - mmseg - INFO - using dpr: linear, 0.2
> 2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm: False
> 2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm_block_ids: None
> 2023-03-28 07:29:30,698 - mmseg - INFO - res_post_norm: False
> /usr/local/lib/python3.8/dist-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
>   warnings.warn(
> load checkpoint from local path: checkpoint_dir/upernet_internimage_t_512_160k_ade20k.pth
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/data_ext/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
>     ret = func(*args, **kwargs)
>   File "/data_ext/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
>     torch_model = task_processor.init_pytorch_model(model_checkpoint)
>   File "/data_ext/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 105, in init_pytorch_model
>     model = init_segmentor(self.model_cfg, model_checkpoint, self.device)
>   File "/usr/local/lib/python3.8/dist-packages/mmseg/apis/inference.py", line 35, in init_segmentor
>     model.CLASSES = checkpoint['meta']['CLASSES']
> KeyError: 'meta'
> 2023-03-28 07:29:32,888 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
> ```

Missing CLASSES information in our released checkpoints seems to be the source of this issue. We will update them as soon as possible to fix this issue. Thank you for your issue!

You can currently run the following code to fix this issue:

```python
import torch
from mmseg.core import get_classes

ckpt_path = '/path/to/ckpt.pth'
ckpt = torch.load(ckpt_path, map_location='cpu')
ckpt['meta'] = {}
ckpt['meta']['CLASSES'] = get_classes('ade20k')

torch.save(ckpt, ckpt_path)
```

**Comment by gongchengli** [comment]
> > > Thank you for your issue.
> > > You can refer to issue #39 to solve this error.
> > 
> > 
> > Thx, now run the deploy.py file and find this,
> > ```
> > 2023-03-28 07:29:30,122 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
> > 2023-03-28 07:29:30,697 - mmseg - INFO - using core type: DCNv3
> > 2023-03-28 07:29:30,698 - mmseg - INFO - using activation layer: GELU
> > 2023-03-28 07:29:30,698 - mmseg - INFO - using main norm layer: LN
> > 2023-03-28 07:29:30,698 - mmseg - INFO - using dpr: linear, 0.2
> > 2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm: False
> > 2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm_block_ids: None
> > 2023-03-28 07:29:30,698 - mmseg - INFO - res_post_norm: False
> > /usr/local/lib/python3.8/dist-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
> >   warnings.warn(
> > load checkpoint from local path: checkpoint_dir/upernet_internimage_t_512_160k_ade20k.pth
> > Process Process-2:
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
> >     self.run()
> >   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
> >     self._target(*self._args, **self._kwargs)
> >   File "/data_ext/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
> >     ret = func(*args, **kwargs)
> >   File "/data_ext/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
> >     torch_model = task_processor.init_pytorch_model(model_checkpoint)
> >   File "/data_ext/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 105, in init_pytorch_model
> >     model = init_segmentor(self.model_cfg, model_checkpoint, self.device)
> >   File "/usr/local/lib/python3.8/dist-packages/mmseg/apis/inference.py", line 35, in init_segmentor
> >     model.CLASSES = checkpoint['meta']['CLASSES']
> > KeyError: 'meta'
> > 2023-03-28 07:29:32,888 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
> > ```
> 
> Missing CLASSES information in our released checkpoints seems to be the source of this issue. We will update them as soon as possible to fix this issue. Thank you for your issue!
> 
> You can currently run the following code to fix this issue:
> 
> ```python
> import torch
> from mmseg.core import get_classes
> 
> ckpt_path = '/path/to/ckpt.pth'
> ckpt = torch.load(ckpt_path, map_location='cpu')
> ckpt['meta'] = {}
> ckpt['meta']['CLASSES'] = get_classes('ade20k')
> 
> torch.save(ckpt, ckpt_path)
> ```

okay, also need to add the PALETTE information by
`ckpt['meta']['PALETTE'] = get_palette('ade20k')`

one more question, I found the size of upernet_internimage_t_512_160k_ade20k.pth is now 112M, which drops a lot compared with the former version (225M). What's the difference between them?

**Comment by Weiyun1025** [comment]
> > > > Thank you for your issue.
> > > > You can refer to issue #39 to solve this error.
> > > 
> > > 
> > > Thx, now run the deploy.py file and find this,
> > > ```
> > > 2023-03-28 07:29:30,122 - mmdeploy - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
> > > 2023-03-28 07:29:30,697 - mmseg - INFO - using core type: DCNv3
> > > 2023-03-28 07:29:30,698 - mmseg - INFO - using activation layer: GELU
> > > 2023-03-28 07:29:30,698 - mmseg - INFO - using main norm layer: LN
> > > 2023-03-28 07:29:30,698 - mmseg - INFO - using dpr: linear, 0.2
> > > 2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm: False
> > > 2023-03-28 07:29:30,698 - mmseg - INFO - level2_post_norm_block_ids: None
> > > 2023-03-28 07:29:30,698 - mmseg - INFO - res_post_norm: False
> > > /usr/local/lib/python3.8/dist-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
> > >   warnings.warn(
> > > load checkpoint from local path: checkpoint_dir/upernet_internimage_t_512_160k_ade20k.pth
> > > Process Process-2:
> > > Traceback (most recent call last):
> > >   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
> > >     self.run()
> > >   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
> > >     self._target(*self._args, **self._kwargs)
> > >   File "/data_ext/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
> > >     ret = func(*args, **kwargs)
> > >   File "/data_ext/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
> > >     torch_model = task_processor.init_pytorch_model(model_checkpoint)
> > >   File "/data_ext/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 105, in init_pytorch_model
> > >     model = init_segmentor(self.model_cfg, model_checkpoint, self.device)
> > >   File "/usr/local/lib/python3.8/dist-packages/mmseg/apis/inference.py", line 35, in init_segmentor
> > >     model.CLASSES = checkpoint['meta']['CLASSES']
> > > KeyError: 'meta'
> > > 2023-03-28 07:29:32,888 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
> > > ```
> > 
> > 
> > Missing CLASSES information in our released checkpoints seems to be the source of this issue. We will update them as soon as possible to fix this issue. Thank you for your issue!
> > You can currently run the following code to fix this issue:
> > ```python
> > import torch
> > from mmseg.core import get_classes
> > 
> > ckpt_path = '/path/to/ckpt.pth'
> > ckpt = torch.load(ckpt_path, map_location='cpu')
> > ckpt['meta'] = {}
> > ckpt['meta']['CLASSES'] = get_classes('ade20k')
> > 
> > torch.save(ckpt, ckpt_path)
> > ```
> 
> okay, also need to add the PALETTE information by `ckpt['meta']['PALETTE'] = get_palette('ade20k')`
> 
> one more question, I found the size of upernet_internimage_t_512_160k_ade20k.pth is now 112M, which drops a lot compared with the former version (225M). What's the difference between them?

We converted the model to half precision to save storage space.

**Comment by czczup** [comment]
Closing this issue as there has been no activity. Please feel free to reopen if required. Thanks for your feedback and support.
