### ISSUE TITLE
我在准备训练时，遇到了这个问题FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpd997prgc/tmpq3k71nwc.py'

### ISSUE THREAD

**Issue by xiaolong-217** [OpenGVLab/InternImage#68]
python train.py ./configs/coco/mask_rcnn_internimage_t_fpn_1x_coco.py --work-dir=./work_dirs --gpu-id 0
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    main()
  File "train.py", line 115, in main
    cfg = Config.fromfile(args.config)
  File "/home/ljw/anaconda3/envs/internimage/lib/python3.7/site-packages/mmcv/utils/config.py", line 338, in fromfile
    use_predefined_variables)
  File "/home/ljw/anaconda3/envs/internimage/lib/python3.7/site-packages/mmcv/utils/config.py", line 251, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ljw/anaconda3/envs/internimage/lib/python3.7/site-packages/mmcv/utils/config.py", line 207, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/ljw/anaconda3/envs/internimage/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpd997prgc/tmpq3k71nwc.py", line 2, in <module>
ImportError: attempted relative import with no known parent package
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f9b21a38950>
Traceback (most recent call last):
  File "/home/ljw/anaconda3/envs/internimage/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/ljw/anaconda3/envs/internimage/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpd997prgc/tmpq3k71nwc.py'
请问你们有遇到过这个问题吗？我尝试了各种方法，目前都无法解决这个问题

**Comment by czczup** [comment]
你好，我遇到过这个问题，可能是因为config里有误触的字符，请问你改过config吗

**Comment by xiaolong-217** [comment]
> 

我在网上查阅这个问题的原因可能就是因为config修改的问题，我确实改过一个config，出现了这个报错。但是之后我在实验其他没有改动过的config时，也出现了这个问题。
