### ISSUE TITLE
ImportError: .local/lib/python3.8/site-packages/DCNv3-1.0-py3.8-linux-x86_64.egg/DCNv3.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll

### ISSUE THREAD

**Issue by fonzen1** [OpenGVLab/InternImage#79]
Whenever I try to train the model I get the following error:

First, my environment:  

NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0  
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
PYTORCH= 1.14.0a0+44dac51

The full error message:

`Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "wandb/mmsegmentation/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "wandb/mmsegmentation/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "wandb/mmsegmentation/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "wandb/mmsegmentation/mmseg/models/backbones/__init__.py", line 23, in <module>
    from .intern_image import InternImage
  File "wandb/mmsegmentation/mmseg/models/backbones/intern_image.py", line 17, in <module>
    from ops_dcnv3 import modules as opsm
  File "wandb/mmsegmentation/ops_dcnv3/modules/__init__.py", line 7, in <module>
    from .dcnv3 import DCNv3, DCNv3_pytorch
  File "wandb/mmsegmentation/ops_dcnv3/modules/dcnv3.py", line 15, in <module>
    from ..functions import DCNv3Function, dcnv3_core_pytorch
  File "mmsegmentation/ops_dcnv3/functions/__init__.py", line 7, in <module>
    from .dcnv3_func import DCNv3Function, dcnv3_core_pytorch
  File "mmsegmentation/ops_dcnv3/functions/dcnv3_func.py", line 17, in <module>
    import DCNv3
ImportError: /home/student.aau.dk/dtran18/.local/lib/python3.8/site-packages/DCNv3-1.0-py3.8-linux-x86_64.egg/DCNv3.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll
`

**Comment by yukiyuki333** [comment]
I also encountered this problem before, but it was resolved when I changed the CUDA version to 11.7, torch==1.13.1, torchvision==0.14.1, torchaudio==0.13.1,and mmsegmentation==0.30.0. Maybe you can try it as well. Hope this helps.

**Comment by Italian-PAO** [comment]
same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well

**Comment by czczup** [comment]
> same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well

Hi, please install PyTorch>=1.10.0.

**Comment by Skyninth** [comment]
same problem while using torch==1.10.1+cu111, 
and ImportError: /~/python3.8/site-packages/DCNv3-1.0-py3.8-linux-x86_64.egg/DCNv3.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

**Comment by JaniceSu-su** [comment]
> > > same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well
> > 
> > 
> > Hi, please install PyTorch>=1.10.0.
> 
> Thank you so much for your quick reply, I have realised this problem and I'm installing PyTorch==1.10.0 Thanks again : )



> > > same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well
> > 
> > 
> > Hi, please install PyTorch>=1.10.0.
> 
> Thank you so much for your quick reply, I have realised this problem and I'm installing PyTorch==1.10.0 Thanks again : )

Hello, have you installed a higher version of Pytorch and resolved the issue ？

**Comment by H-Ambrose** [comment]
> > > > same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well
> > > 
> > > 
> > > Hi, please install PyTorch>=1.10.0.
> > 
> > 
> > Thank you so much for your quick reply, I have realised this problem and I'm installing PyTorch==1.10.0 Thanks again : )
> 
> > > > same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well
> > > 
> > > 
> > > Hi, please install PyTorch>=1.10.0.
> > 
> > 
> > Thank you so much for your quick reply, I have realised this problem and I'm installing PyTorch==1.10.0 Thanks again : )
> 
> Hello, have you installed a higher version of Pytorch and resolved the issue ？



> > > > same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well
> > > 
> > > 
> > > Hi, please install PyTorch>=1.10.0.
> > 
> > 
> > Thank you so much for your quick reply, I have realised this problem and I'm installing PyTorch==1.10.0 Thanks again : )
> 
> > > > same problem while using torch==1.9.1+cu111, and ./make.sh doesnt work as well
> > > 
> > > 
> > > Hi, please install PyTorch>=1.10.0.
> > 
> > 
> > Thank you so much for your quick reply, I have realised this problem and I'm installing PyTorch==1.10.0 Thanks again : )
> 
> Hello, have you installed a higher version of Pytorch and resolved the issue ？

hello! After change torch==1.11.0+cu113 to 1.13.1+cu117, I encountered the same error. Have you resolved the issue😟
